import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <main className="flex min-h-screen flex-col gap-12 p-24 pt-0">about</main>
  );
}
