import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const items = [
  { name: "home", url: "/" },
  { name: "projetos", url: "/projects" },
  { name: "sobre", url: "/about" },
  { name: "objetivos", url: "/objectives" },
  { name: "planner", url: "/planner" },
  { name: "blog", url: "/blog" },
  { name: "weeklyCheck", url: "/weeklyCheck" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col gap-12 p-24 pt-0">
          <Header />
          <Nav items={items} />
          {children}
        </main>
      </body>
    </html>
  );
}
